// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { AccountInfo, AccountInfoTableId } from "./tables/AccountInfo.sol";
import { BattleCounter, BattleCounterTableId } from "./tables/BattleCounter.sol";
import { BattleInfo, BattleInfoTableId } from "./tables/BattleInfo.sol";
import { CardCounter, CardCounterTableId } from "./tables/CardCounter.sol";
import { CharacterSheetInfo, CharacterSheetInfoTableId } from "./tables/CharacterSheetInfo.sol";
import { MapConfig, MapConfigTableId } from "./tables/MapConfig.sol";
import { MolochSoldier, MolochSoldierTableId } from "./tables/MolochSoldier.sol";
import { Movable, MovableTableId } from "./tables/Movable.sol";
import { Obstruction, ObstructionTableId } from "./tables/Obstruction.sol";
import { PartyInfo, PartyInfoTableId } from "./tables/PartyInfo.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { TradeInfo, TradeInfoTableId } from "./tables/TradeInfo.sol";
