// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IBattleSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IBattleSystem {
  function attack(address playerAddress, bytes32 molochSoldier, uint32 power) external;

  function initiateBattle(address playerAddress, uint32 x, uint32 y) external;
}
