// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IMapSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMapSystem {
  function attack(uint32 x, uint32 y) external;

  function spawn(uint32 x, uint32 y, uint256 chainId, address gameAddress, address playerAddress) external;

  function logout() external;

  function move(uint32 x, uint32 y) external;
}
